CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY IDENTITY(1,1),
	FIRST_NAME NVARCHAR(255),
	LAST_NAME NVARCHAR(255),
	STD_NUM NVARCHAR(255),
	CYS NVARCHAR(255),
	USERNAME NVARCHAR(255),
	EMAIL NVARCHAR(255),
	PASSWORD NVARCHAR(255)
	);
